apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chatapp-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chatapp-deployment   # Replace with your deployment name
  minReplicas: 2               # Minimum number of pods
  maxReplicas: 10              # Maximum number of pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50   # Target CPU utilization %
